### PR TITLE
qubes-builder integration

### PR DESCRIPTION
**Pull request by marmarek**

### CODE REVIEW

**Comment by fepitre** [comment]
@marmarek: do you simply do a 'make get-sources-git'? a usual 'make get-sources' produces errors when it's processing 'additional sources': ```./usr/share/genmkfile/make-helper-one.bsh: line 1399: get-sources: command not found```.

**Comment by adrelanos** [comment]
genmkfile `Makefile` conflicts with Qubes `Makefile` looks like.

https://github.com/Whonix/security-misc/blob/master/Makefile (version 1.5)

https://github.com/Whonix/genmkfile/blob/master/Makefile (version 1.7 actually considering to downgrade to 1.5 for simplification)

Kinda genmkfile `Makefile` vs upstream `Makefile`.

Generally super simple if upstream is me and just packaging configuration files and scripts. genmkfile support for compiled code or upstream not wanting to adapt it is not that great yet but a few examples:

* In case of kloak (compiled code), upstream liked genmkfile based packaging so we appended genmkfile to `Makefile` by upstream and merged upstream. - https://github.com/Whonix/kloak/blob/master/Makefile
* In case of corridor, upstream did not like to adapt genmkfile, I renamed upstream `Makefile` to `Makefile_orig` and genmkfile became `Makefile . - https://github.com/Whonix/corridor
* For hardened_malloc, it is yet to be seen how to best combine genmkfile with upstream Makefile.
  * genmkfile on top of upstream Makefile (in same file) allows upstream to implement `make clean` but shows a warning that "original" (i.e. by genmkfile) make clean target got overwritten. Not ideal but works.
  * genmkfile below below Makefile (in same file) breaks upstream `make clean`.
  * renaming Makefile to Makefile_orig (upstream version) works but it is not a nice patch to carry when upstream keeps updating Makefile (unless upstream likes merging genmkfile)
  * https://github.com/GrapheneOS/hardened_malloc/pull/90
  * currently a simple `make` (in `debian` branch) no longer builds it (without packaging), in other words `make` default target `all` needs to be revised inside genmkfile.
  * maybe genmkfile should stay out of (not implement) `make clean` and `make all` but I have to check if this is compatible with the other Debian packages already existing (Debian packaging tools might by default run `make all` during packaging).
  * Or a genmkfile for scripts and a "reduced" one for compiled code.

Btw genmkfile is based on `make` not because I like `make` (I'd rather not use it if I'd find some solution) because Debian packaging requires it since it does things like set `DESTDIR` environment variable and run `make install `.

**Comment by adrelanos** [comment]
> a usual 'make get-sources' produces errors when it's processing 'additional sources': ./usr/share/genmkfile/make-helper-one.bsh: line 1399: get-sources: command not found.

Meaning, that genmkfile `Makefile` is in use which does not know about that 'make get-sources'.

Where is the Makefile that is producing that error? Like described above, we somehow need to either merge genmkfile Makefile and Qubes makefile for that package or solve the interaction another way by renaming Qubes one to Makefile_orig or otherwise.

**Comment by fepitre** [comment]
@adrelanos: from qubes-builder call ```make get-sources```, it recursively calls the Makefile in each source, which is in this case https://github.com/Whonix/genmkfile/blob/master/Makefile. The error is produced when calling the Makefile with 'get-sources-extra', which is done just after fetching the sources.

In order to build the package for Fedora, I only did in the ```qubes-builder```, ```make get-sources-git``` to fetch only the source and then ```make genmkfile```.

@marmarek: do you have this trouble too?

**Comment by marmarek** [comment]
Yes, same problem here. qubes-builder checks if `get-sources` target is defined before calling it, but since gemkfile defines wildcard target (`%`), that check passes so `make get-sources` gets called even though it isn't really valid.
To be honest, `makefile-full` looks inconsistent - it lists a lot of targets explicitly, but then there is a wildcard doing exactly the same thing as other targets. Is there any reason for that wildcard? If yes, then why other targets (with the same content) are listed anyway?

As for qubes-builder integration, I see multiple options, depending on the answer of the above:
 - modify qubes-builder to exclude wildcards when checking for `get-sources` target (similar to what bash completion does)
 - remove wildcard from genmkfile's makefile, so it's properly detected by the current qubes-builder
 - add empty `get-sources` and `verify-sources` targets(*) (with an option to override per component) - this would solve the problem regardless of the wildcard, but could possibly interfere with existing or future real `get-sources` target)

(*) if `get-sources` is there, `verify-sources` is called too. In many places we've moved download verification to `get-sources` that remove downloaded files if verification failed, but to be on the safe side, `verify-sources` is still called.

**Comment by adrelanos** [comment]
Marek Marczykowski-Górecki:
> To be honest, `makefile-full` looks inconsistent - it lists a lot of targets explicitly, but then there is a wildcard doing exactly the same thing as other targets.


Yes, happy to see improvements here.

> Is there any reason for that wildcard? If yes, then why other targets (with the same content) are listed anyway?


The idea probably was to call the make target of the upstream makefile.


> As for qubes-builder integration, I see multiple options, depending on the answer of the above:
>  - modify qubes-builder to exclude wildcards when checking for `get-sources` target (similar to what bash completion does)
>  - add empty `get-sources` and `verify-sources` targets(*) (with an
option to override per component) - this would solve the problem
regardless of the wildcard, but could possibly interfere with existing
or future real `get-sources` target)
>
> (*) if `get-sources` is there, `verify-sources` is called too. In many
places we've moved download verification to `get-sources` that remove
downloaded files if verification failed, but to be on the safe side,
`verify-sources` is still called.


Hopefully not required. genmkfile is an additional dependency (not
available form package.debian.org) which already makes it a bit
intrusive. genmkfile ideally will give upstream a really simple time
with one short appendix to their makefile to get all the packaging and
maintenance features the can be reasonably encapsulated and provided in
such a tool.

>  - remove wildcard from genmkfile's makefile, so it's properly detected by the current qubes-builder


I guess that will be it.

Just noticed with the hardened malloc package that the first make target
is the first defined make target since a simple "make" resulted in "make
dist" (first in genmkfile makefile-full) rather than creating
hardened_malloc shared object. That suggests to add genmkfile at the
bottom of an upstream make file rather than on top.

Therefore I am experimenting removing from genmkfile makefile-full:

- make all
- make clean
- and the wild card.

The plan is to bend genmkfile so upstream needs as little changes as
possible.

This is implemented in genmkfile git master.

**Comment by adrelanos** [comment]
Latest git tag has this and it's in Whonix developers repository
already. Please let me know if further changes in genmkfile are needed.

**Pull request merged**
